version: "3"
services:
  ipersona_prod:
    container_name: ipersona_prod
    build: .
    image: ipersona_prod:latest
    restart: unless-stopped
    environment:
      - STRAPI_STAGE=dev-prod
      - PORT=4900
      - APP_MODULE=app:app
      - WORKERS_PER_CORE=0.5
      - TIMEOUT=120
      - KEEP_ALIVE=60
      - LOG_LEVEL=info      
      - AWS_ACCESS_KEY_ID=AKIARAUQOUIFYWMG4XLG
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=us-east-1

    networks:
      - ipersona_network    
    # volumes:
    #   - /mnt/efs:/mnt/efs
    expose:
      - 4900 
    ports:
      - "4900:4900"

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile.celery
    image: celery_worker:latest
    restart: unless-stopped
    environment:
      - STRAPI_STAGE=dev-prod
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis.10academy.org:6379/0
      - AWS_ACCESS_KEY_ID=AKIARAUQOUIFYWMG4XLG
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - ipersona_network
    depends_on:
      - ipersona_prod

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: Dockerfile.celery
    image: celery_worker:latest
    restart: unless-stopped
    environment:
      - STRAPI_STAGE=dev-prod
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis.10academy.org:6379/0
    networks:
      - ipersona_network
    ports:
      - "5555:5555"
    command: ["/app/start_flower.sh"]
    depends_on:
      - celery_worker

networks:
    ipersona_network:
        name: ipersona_prod
        driver: bridge      

