version: "3"
services:
  ipersona:
    container_name: ipersona
    build: .
    image: ipersona:latest
    restart: unless-stopped
    environment:
      - STRAPI_STAGE=dev
      - PORT=4500
      - APP_MODULE=app:app
      - WORKERS_PER_CORE=0.5
      - TIMEOUT=120
      - KEEP_ALIVE=60
      - LOG_LEVEL=info      
      - AWS_ACCESS_KEY_ID=AKIARAUQOUIFYWMG4XLG
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=us-east-1

    networks:
      - ipersona_network    
    # volumes:
    #   - /mnt/efs:/mnt/efs
    expose:
      - 4500 
    ports:
      - "4500:4500"

networks:
    ipersona_network:
        name: ipersona
        driver: bridge      

